apiVersion: v1
kind: Service

metadata:
  name: mongodb-service
  namespace: mongodb
  labels:
    name: mongodb-service
spec:
  type: LoadBalancer
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongodb-service
  selector:
    name: mongo-node1
    instance: rod